name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Derivation
      run: nix flake check
    - name: Build Derivation
      run: nix build
    - name: Test SS14.Launcher
      run: nix develop --command bash -c "dotnet test SS14.Launcher.Tests/SS14.Launcher.Tests.csproj -v n"
